from PyQt5 import QtCore, QtWidgets

from app.consts import RED_ROSE


class UiTab2(QtWidgets.QWidget):

    def setupUi(self, MainWindow):
        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 360, 1001, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.button_rose = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_rose.setObjectName("button_rose")
        self.gridLayout_7.addWidget(self.button_rose, 0, 0, 1, 1)
        self.button_duration_wind = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_duration_wind.setObjectName("button_duration_wind")
        self.gridLayout_7.addWidget(self.button_duration_wind, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 5, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.button_conditions = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_conditions.setObjectName("button_conditions")
        self.gridLayout_6.addWidget(self.button_conditions, 1, 0, 1, 1)
        self.button_duration_temperature = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_duration_temperature.setObjectName("button_duration_temperature")
        self.gridLayout_6.addWidget(self.button_duration_temperature, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 5, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.button_export_pdf = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_export_pdf.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.button_export_pdf, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 5, 4, 1, 1)
        self.calendar_from = QtWidgets.QCalendarWidget(self)
        self.calendar_from.setGeometry(QtCore.QRect(350, 50, 351, 293))
        self.calendar_from.setMaximumSize(QtCore.QSize(400, 400))
        self.calendar_from.setObjectName("calendar_from")
        self.calendar_to = QtWidgets.QCalendarWidget(self)
        self.calendar_to.setGeometry(QtCore.QRect(730, 50, 351, 293))
        self.calendar_to.setMaximumSize(QtCore.QSize(400, 400))
        self.calendar_to.setObjectName("calendar_to")
        self.button_import_regions = QtWidgets.QPushButton(self)
        self.button_import_regions.setGeometry(QtCore.QRect(20, 130, 311, 29))
        self.button_import_regions.setObjectName("button_import_regions")
        self.comboBox = QtWidgets.QComboBox(self)
        self.comboBox.setGeometry(QtCore.QRect(20, 210, 311, 28))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(500, 20, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(880, 20, 63, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate(RED_ROSE, "Date from"))
        self.label_2.setText(_translate(RED_ROSE, "Date to"))
        self.button_import_regions.setText(_translate(RED_ROSE, "Import regions"))
        self.button_conditions.setText(_translate(RED_ROSE, "Temperature conditions"))
        self.button_import_regions.setText(_translate(RED_ROSE, "Import regions"))
        self.button_duration_temperature.setText(_translate(RED_ROSE, "Duration of temperature regimes"))
        self.button_duration_wind.setText(_translate(RED_ROSE, "Duration of wind activity modes"))
        self.button_rose.setText(_translate(RED_ROSE, "Rose of the winds"))
        self.button_export_pdf.setText(_translate(RED_ROSE, "Export pdf file"))